export const COUNTRIES_FETCH_REQUEST = 'COUNTRIES_FETCH_REQUEST';
export const COUNTRIES_FETCH_SUCCESS = 'COUNTRIES_FETCH_SUCCESS';
export const COUNTRIES_FETCH_FAILURE = 'COUNTRIES_FETCH_FAILURE';
export const COUNTRIES_FILTER = 'COUNTRIES_FILTER';
