export const REGIONS_FETCH_REQUEST = 'REGIONS_FETCH_REQUEST';
export const REGIONS_FETCH_SUCCESS = 'REGIONS_FETCH_SUCCESS';
export const REGIONS_FETCH_FAILURE = 'REGIONS_FETCH_FAILURE';
export const REGIONS_FILTER = 'REGIONS_FILTER';
export const COUNTRY_FETCH_SUCCESS = 'COUNTRY_FETCH_SUCCESS';
